name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          target_name: 'pfp-cli'
        - os: windows-latest
          target_name: 'pfp-cli.exe'
        - os: macos-latest
          target_name: 'pfp-cli'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release --verbose
    - name: Strip symbols
      run: strip target/release/${{ matrix.target_name }}
    - name: Upload pfp-cli artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.target_name }} ${{ matrix.os }}
        path: target/release/${{ matrix.target_name }}
    - name: Run tests
      run: cargo test --verbose
    - name: Build (size-optimized)
      run: cargo build --release --verbose --features sizeoptimized
      env:
        CARGO_PROFILE_RELEASE_OPT_LEVEL: z
    - name: Strip symbols (size-optimized)
      run: strip target/release/${{ matrix.target_name }}
    - name: Upload pfp-cli-sizeoptimized artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.target_name }}-sizeoptimized ${{ matrix.os }}
        path: target/release/${{ matrix.target_name }}
    - name: Run tests (size-optimized)
      run: cargo test --verbose --features sizeoptimized
